{% set name = "asimov" %}
{% set version = "0.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06d2cdc751fb7f5bec57dd144a04903ebb8c34a181153f9a80c61e26fee8c681

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - locutus=asimov.locutus:cli
    - olivaw=asimov.olivaw:olivaw
    - asimov=asimov.olivaw:olivaw

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - click
    - flask
    - git
    - gitpython
    - gwpy
    - igwn-auth-utils
    - ligo-gracedb
    - liquidpy
    - lscsoft-glue
    - networkx
    - numpy
    - otter-report >=0.3.3
    - python >={{ python_min }}
    - python-gitlab
    - python-htcondor
    - pytz
    - pyyaml
    - requests
    - tinydb

test:
  requires:
    - pip
    - git
    - python {{ python_min }}
  imports:
    - asimov
  commands:
    # check requirements
    - python -m pip check
    # check entry points
    - locutus --help
    - asimov --help
    - olivaw --help

about:
  home: https://asimov.docs.ligo.org/asimov/
  doc_url: https://asimov.docs.ligo.org/asimov/
  dev_url: https://git.ligo.org/asimov/asimov.git
  license: ISC
  license_file: LICENSE
  summary: Parameter Estimation automator for gravitational wave analyses.
  description: |
    Asimov is a python package designed to make organising and monitoring data analysis jobs easier.

extra:
  recipe-maintainers:
    - transientlunatic
    - duncanmmacleod
