{% set name = "asimov" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa14713f6c1d148b74e8d6fa781d40a3d0d825eb7f3554e72acfc8ef26ca45a1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - locutus=asimov.locutus:cli
    - olivaw=asimov.olivaw:olivaw
    - asimov=asimov.olivaw:olivaw

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - setuptools_scm
  run:
    - click
    - flask
    - git
    - gitpython
    - gwpy
    - igwn-auth-utils
    - ligo-gracedb
    - liquidpy
    - lscsoft-glue
    - networkx
    - numpy
    - otter-report >=0.3.3
    - python >=3.7
    - python-gitlab
    - python-htcondor
    - pytz
    - pyyaml
    - requests
    - tinydb

test:
  requires:
    - pip
    - git
  imports:
    - asimov
  commands:
    # check requirements
    - python -m pip check
    # check entry points
    - locutus --help
    - asimov --help
    - olivaw --help

about:
  home: https://asimov.docs.ligo.org/asimov/
  doc_url: https://asimov.docs.ligo.org/asimov/
  dev_url: https://git.ligo.org/asimov/asimov.git
  license: ISC
  license_file: LICENSE
  summary: Parameter Estimation automator for gravitational wave analyses.
  description: |
    Asimov is a python package designed to make organising and monitoring data analysis jobs easier.

extra:
  recipe-maintainers:
    - transientlunatic
    - duncanmmacleod
